import { useEffect,useState } from 'react';
import { ArrowLeft, Link2, RefreshCw, ShieldCheck, WalletCards } from 'lucide-react';
import { Link,useLocation } from 'react-router-dom';
import { toast } from 'sonner';
import { quickbiteApi } from '../../../services/api/quickbiteApi';

export function CoreParentFeaturePage(){
 const path=useLocation().pathname; const [family,setFamily]=useState<any[]>([]); const [data,setData]=useState<any>(null); const [selected,setSelected]=useState(''); const [loading,setLoading]=useState(true); const [code,setCode]=useState(''); const [limits,setLimits]=useState({dailyLimit:'',weeklyLimit:'',monthlyLimit:''});
 const load=async()=>{setLoading(true);try{const f=await quickbiteApi().parentFamily();setFamily(f.items??[]);const sid=selected||f.items?.[0]?.student_id||'';if(sid) {setSelected(sid);setData(path.includes('food-controls')?await quickbiteApi().parentFoodControls(sid):path.includes('wellbeing')?await quickbiteApi().parentWellbeing(sid):f);}}catch(e){toast.error(e instanceof Error?e.message:'No se pudo cargar.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[path,selected]); if(loading)return <div className="grid min-h-screen place-items-center"><RefreshCw className="h-6 w-6 animate-spin"/></div>;
 const title=path.includes('food-controls')?'Controles alimentarios':path.includes('wellbeing')?'Bienestar y límites':'Mi familia';
 return <main className="qb-page min-h-screen p-5 sm:p-8"><div className="mx-auto max-w-5xl space-y-5"><div><Link to="/parent/family" className="inline-flex items-center gap-2 text-xs font-black text-emerald-700"><ArrowLeft className="h-4 w-4"/>Familia</Link><h1 className="mt-2 qb-text text-3xl font-black">{title}</h1></div>
 {path.includes('family')&&<><section className="qb-surface rounded-3xl border qb-border p-6"><div className="flex gap-3"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="QB-..." className="flex-1 rounded-xl border qb-border bg-transparent px-3 py-2"/><button onClick={async()=>{try{await quickbiteApi().linkParentFamily(code);toast.success('Vínculo creado.');setCode('');await load()}catch(e){toast.error(e instanceof Error?e.message:'Código inválido.')}}} className="rounded-xl bg-emerald-600 px-4 py-2 font-black text-white"><Link2 className="mr-2 inline h-4 w-4"/>Vincular</button></div></section><div className="grid gap-4 md:grid-cols-2">{family.map(c=><article key={c.student_id} className="qb-surface rounded-3xl border qb-border p-5"><ShieldCheck className="h-5 w-5 text-emerald-500"/><h2 className="qb-text mt-3 font-black">{c.full_name}</h2><p className="qb-text-secondary text-sm">{c.email}</p><p className="qb-text-secondary mt-1 text-sm">{[c.section,c.grade,c.course].filter(Boolean).join(' · ')}</p></article>)}</div></>}
 {path.includes('food-controls')&&<><div className="qb-surface rounded-3xl border qb-border p-4"><label className="qb-text text-sm font-black">Estudiante <select className="ml-2 rounded-xl border qb-border bg-transparent px-3 py-2" value={selected} onChange={e=>setSelected(e.target.value)}>{family.map(c=><option key={c.student_id} value={c.student_id}>{c.full_name}</option>)}</select></label></div><div className="grid gap-3">{(data?.items??[]).map((p:any)=><article key={p.id} className="qb-surface flex items-center justify-between rounded-3xl border qb-border p-4"><div><p className="qb-text font-black">{p.name}</p><p className="qb-text-secondary text-sm">{p.category_name}</p></div><button onClick={async()=>{try{await quickbiteApi().setParentFoodBlock({studentId:selected,productId:p.id,blocked:!p.blocked,reason:'Control familiar'});await load()}catch(e){toast.error(e instanceof Error?e.message:'No se pudo actualizar.')}}} className="rounded-xl border px-4 py-2 text-sm font-black">{p.blocked?'Desbloquear':'Bloquear'}</button></article>)}</div></>}
 {path.includes('wellbeing')&&<><div className="grid gap-4 md:grid-cols-3">{[['Hoy',data?.spending?.today],['Semana',data?.spending?.week],['Mes',data?.spending?.month]].map(x=><div key={String(x[0])} className="qb-surface rounded-3xl border qb-border p-5"><p className="qb-text-secondary text-sm">{x[0]}</p><p className="mt-1 text-2xl font-black text-emerald-600">{'$'+Number(x[1]||0).toLocaleString('es-CO')}</p></div>)}</div><section className="qb-surface rounded-3xl border qb-border p-6"><h2 className="qb-text text-xl font-black">Límites de gasto</h2><div className="mt-4 grid gap-3 md:grid-cols-3">{['dailyLimit','weeklyLimit','monthlyLimit'].map(k=><input key={k} className="rounded-xl border qb-border bg-transparent px-3 py-2" placeholder={k} value={(limits as any)[k]} onChange={e=>setLimits({...limits,[k]:e.target.value})}/>)}</div><button onClick={async()=>{try{await quickbiteApi().setParentSpendingLimits({studentId:selected,dailyLimit:limits.dailyLimit?Number(limits.dailyLimit):null,weeklyLimit:limits.weeklyLimit?Number(limits.weeklyLimit):null,monthlyLimit:limits.monthlyLimit?Number(limits.monthlyLimit):null});toast.success('Límites guardados.');}catch(e){toast.error(e instanceof Error?e.message:'No se pudo guardar.')}}} className="mt-4 rounded-xl bg-blue-600 px-5 py-2 font-black text-white"><WalletCards className="mr-2 inline h-4 w-4"/>Guardar límites</button></section></>}
 </div></main>;
}
