import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Eye, EyeOff, GraduationCap, Loader2, Lock, Mail, ShieldCheck, Users } from 'lucide-react';
import { useAuthStore } from '../../store/authStore';
import { requireSupabaseClient, setAuthContext } from '../../lib/supabase';
import { getProfile } from '../../repositories/quickbiteRepository';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { Label } from '../components/ui/label';
import { canAccessParent, canAccessStudent, canAccessAdmin } from '../../lib/access';
import { QuickBiteLogo } from '../components/brand/QuickBiteLogo';
import { bindStudentUser, clearBoundStudentUser, getBoundStudentUserId } from '../../lib/studentDeviceSession';
import { toast } from 'sonner';

type Mode='student'|'parent'|'admin'; type LoginIntent='student'|'parent'|'admin';
export function LoginPage(){
 const navigate=useNavigate(); const{setUser}=useAuthStore(); const previewRole=typeof window!=='undefined'?new URLSearchParams(window.location.search).get('preview_role'):null; const initialMode:Mode=previewRole==='admin'||previewRole==='parent'||previewRole==='student'?previewRole:'student';
 const[mode,setMode]=useState<Mode>(initialMode); const[email,setEmail]=useState(''); const[password,setPassword]=useState(''); const[showPassword,setShowPassword]=useState(false); const[loading,setLoading]=useState(false); const[error,setError]=useState('');
 const handleLogin=async(event:React.FormEvent,intent:LoginIntent=mode)=>{event.preventDefault();setError('');if(!email||!password){setError('Ingresa correo y contraseña.');return;}setLoading(true);try{setAuthContext(intent==='admin'?'admin':'user');await useAuthStore.getState().signIn(email,password);const profile=useAuthStore.getState().user;if(!profile){throw new Error('No se pudo cargar tu perfil de QuickBite.');}if(intent==='admin'){if(!canAccessAdmin(profile.role)){await useAuthStore.getState().signOut();throw new Error('Esta cuenta no tiene acceso administrativo.');}navigate('/admin');toast.success('Bienvenido a Administración.');return;}if(intent==='parent'){if(!canAccessParent(profile.role)){await useAuthStore.getState().signOut();throw new Error('Esta cuenta no tiene acceso de Padre de Familia.');}navigate('/parent/family');toast.success('Bienvenido a QuickBite Family.');return;}if(!canAccessStudent(profile.role)){await useAuthStore.getState().signOut();throw new Error('Esta cuenta no tiene acceso de estudiante.');}const boundUserId=getBoundStudentUserId();if(boundUserId&&boundUserId!==profile.id){await useAuthStore.getState().signOut();throw new Error('Este dispositivo ya está vinculado a otra cuenta de estudiante. Usa “Cambiar estudiante en este dispositivo”.');}bindStudentUser(profile.id);navigate('/menu');toast.success('Bienvenido.');}catch(err){const message=err instanceof Error?err.message:'No se pudo iniciar sesión.';setError(message);toast.error(message);}finally{setLoading(false)}}; const changeStudentOnDevice=async()=>{setAuthContext('user');const client=requireSupabaseClient();await client.auth.signOut();clearBoundStudentUser();setUser(null);setEmail('');setPassword('');setError('');toast.success('Este dispositivo ya puede vincularse a otro estudiante.');}; const isStudent=mode==='student'; const isParent=mode==='parent'; const studentIsBound=Boolean(getBoundStudentUserId());
 const roleAccent = isStudent ? 'green' : isParent ? 'blue' : 'admin';
 return <div data-qb-auth-mode={roleAccent} className={`qb-auth qb-auth--${roleAccent} min-h-screen flex flex-col items-center justify-center p-5 transition-colors duration-500`}><div className="w-full max-w-sm relative z-10"><div className="qb-auth-brand text-center mb-7"><QuickBiteLogo className="mb-3 h-[4.5rem] w-[4.5rem] rounded-3xl"/><h1 className="qb-auth-brand-title text-3xl font-bold tracking-tight">QuickBite</h1><p className="qb-auth-brand-subtitle text-sm mt-1">{isStudent?'Portal estudiante':isParent?'Portal padre de familia':'Portal administrativo'}</p></div><div className="qb-auth-card rounded-3xl shadow-2xl p-7">
 {isStudent&&<div className="mb-5"><div className="flex items-center gap-2 mb-3"><GraduationCap className="qb-auth-role-icon w-5 h-5"/><h2 className="text-lg font-bold">Estudiante</h2></div><div className="qb-auth-switch grid grid-cols-2 gap-2 rounded-2xl p-1"><button type="button" onClick={()=>{setMode('student');setAuthContext('user');setError('')}} className="flex items-center justify-center gap-2 rounded-xl py-2.5 text-sm font-semibold"><GraduationCap className="w-4 h-4"/>Iniciar sesión como estudiante</button><button type="button" onClick={()=>{setMode('parent');setAuthContext('user');setError('')}} className="flex items-center justify-center gap-2 rounded-xl py-2.5 text-sm font-semibold"><Users className="w-4 h-4"/>Iniciar sesión como padre</button></div></div>}
 {isParent&&<div className="mb-5"><div className="flex items-center gap-2 mb-3"><Users className="qb-auth-role-icon w-5 h-5"/><h2 className="text-lg font-bold">Padre de familia</h2></div><button type="button" onClick={()=>{setMode('student');setAuthContext('user');setError('')}} className="qb-auth-switch-button flex w-full items-center justify-center gap-2 rounded-xl py-2.5 text-sm font-semibold"><GraduationCap className="w-4 h-4"/>Iniciar sesión como estudiante</button><div className="qb-auth-active-note mt-2 rounded-xl px-3 py-2 text-xs">Iniciar sesión como padre</div></div>}
 {!isStudent&&!isParent&&<div className="mb-5 flex items-center gap-2"><ShieldCheck className="qb-auth-role-icon w-5 h-5"/><h2 className="text-lg font-bold">Administración</h2></div>}
 <form onSubmit={event=>void handleLogin(event,mode)} autoComplete="on" className="space-y-4"><div><h3 className="text-xl font-bold mb-1">{isStudent?'Iniciar sesión como estudiante':isParent?'Iniciar sesión como padre':'Iniciar sesión como admin'}</h3><p className="text-sm mb-5">{isStudent?'Accede al menú y a tu cuenta de estudiante.':isParent?'Accede a los estudiantes vinculados.':'Acceso solo para administradores.'}</p><Label htmlFor="login-email" className="text-sm mb-1 block">Correo electrónico</Label><div className="relative"><Mail className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4"/><Input name="email" autoComplete="username" id="login-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} className="pl-9"/></div></div><div><div className="flex items-center justify-between mb-1"><Label htmlFor="login-password" className="text-sm">Contraseña</Label>{(isStudent||isParent)&&<Link to="/forgot-password" className="qb-auth-link text-xs underline underline-offset-2">Recuperar</Link>}</div><div className="relative"><Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4"/><Input name="current-password" autoComplete="current-password" id="login-password" type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} className="pl-9 pr-10"/><button type="button" onClick={()=>setShowPassword(!showPassword)} className="qb-auth-icon-button absolute right-2 top-1/2 -translate-y-1/2">{showPassword?<EyeOff className="w-4 h-4"/>:<Eye className="w-4 h-4"/>}</button></div>{error&&<p className="qb-auth-error text-xs mt-1">{error}</p>}</div><Button type="submit" disabled={loading} className="qb-auth-primary w-full font-semibold py-6 rounded-xl">{loading?<><Loader2 className="w-4 h-4 mr-2 animate-spin"/>Entrando...</>:'Iniciar sesión'}</Button>{isStudent&&studentIsBound&&<Button type="button" variant="ghost" onClick={()=>void changeStudentOnDevice()} disabled={loading} className="qb-auth-secondary-action w-full text-xs">Cambiar estudiante en este dispositivo</Button>}{isStudent&&<Link to="/register-student"><Button type="button" variant="outline" className="qb-auth-secondary w-full py-5 rounded-xl text-sm">Crear cuenta de estudiante</Button></Link>}{isParent&&<Link to="/register-parent"><Button type="button" variant="outline" className="qb-auth-secondary w-full py-5 rounded-xl text-sm">Crear cuenta de Padre de Familia</Button></Link>}{(isStudent||isParent)&&<Button type="button" variant="outline" onClick={()=>{setMode('admin');setAuthContext('admin');setError('')}} className="qb-auth-secondary w-full py-5 rounded-xl text-sm">Acceso de administración</Button>}{mode==='admin'&&<Button type="button" variant="outline" onClick={()=>{setMode('student');setAuthContext('user');setError('')}} className="qb-auth-secondary w-full py-5 rounded-xl text-sm">Volver a Estudiante</Button>}</form></div></div></div>;
}