import { useEffect,useState } from 'react';
import { ArrowLeft, Bell, Heart, Link2, RefreshCw, Star } from 'lucide-react';
import { Link,useLocation } from 'react-router-dom';
import { toast } from 'sonner';
import { quickbiteApi } from '../../../services/api/quickbiteApi';

const money=(n:number)=>'$'+Number(n||0).toLocaleString('es-CO');
const screenTitle=(p:string)=>p.includes('wallet')?'Saldos y recargas':p.includes('history')?'Pedidos':p.includes('favorites')?'Mis favoritos':p.includes('notifications')?'Notificaciones':p.includes('reviews')?'Reseñas y calificaciones':p.includes('rewards')?'Puntos y premios':p.includes('link-code')?'Código familiar':'Mi cuenta';

export function CoreStudentFeaturePage(){
 const path=useLocation().pathname;
 const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null);
 const [topup,setTopup]=useState({amount:'',method:'manual',reference:'',comment:''});
 const [account,setAccount]=useState({fullName:'',dietaryPreferences:'',allergies:'',guardianNotes:''});
 const [review,setReview]=useState<Record<string,{stars:number;comment:string}>>({});
 const load=async()=>{setLoading(true);try{if(path.includes('/wallet'))setData(await quickbiteApi().walletDetails());else if(path.includes('/favorites'))setData(await quickbiteApi().studentFavorites());else if(path.includes('/notifications'))setData(await quickbiteApi().notifications());else if(path.includes('/reviews'))setData(await quickbiteApi().studentReviews());else if(path.includes('/rewards'))setData(await quickbiteApi().studentRewards());else if(path.includes('/link-code'))setData(await quickbiteApi().studentLinkCode());else setData(await quickbiteApi().studentAccount());}catch(e){toast.error(e instanceof Error?e.message:'No se pudo cargar la función.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[path]); useEffect(()=>{if(data?.user)setAccount(a=>({...a,fullName:data.user.full_name??data.user.fullName??''}))},[data]);
 if(loading)return <div className="grid min-h-screen place-items-center qb-page"><RefreshCw className="h-6 w-6 animate-spin"/></div>;
 const saveAccount=async()=>{setBusy('account');try{await quickbiteApi().updateStudentAccount({fullName:account.fullName,dietaryPreferences:account.dietaryPreferences.split(',').map(x=>x.trim()).filter(Boolean),allergies:account.allergies,guardianNotes:account.guardianNotes});toast.success('Cuenta actualizada.');await load()}catch(e){toast.error(e instanceof Error?e.message:'No se pudo guardar la cuenta.')}finally{setBusy(null)}};
 const sendTopup=async()=>{const amount=Number(topup.amount);if(!amount||amount<=0)return toast.error('Ingresa un valor válido.');setBusy('topup');try{await quickbiteApi().requestWalletTopup({...topup,amount,method:topup.method as any});toast.success('Solicitud enviada para revisión.');setTopup({amount:'',method:'manual',reference:'',comment:''});await load()}catch(e){toast.error(e instanceof Error?e.message:'No se pudo solicitar la recarga.')}finally{setBusy(null)}};
 return <main className="qb-page min-h-screen p-5 sm:p-8"><div className="mx-auto max-w-5xl space-y-5"><div className="flex items-center justify-between"><div><Link to="/student/features" className="inline-flex items-center gap-2 text-xs font-black text-emerald-700"><ArrowLeft className="h-4 w-4"/>Funciones</Link><h1 className="mt-2 qb-text text-3xl font-black">{screenTitle(path)}</h1></div><button onClick={()=>void load()} className="rounded-xl border qb-border qb-surface px-4 py-2 text-sm font-black"><RefreshCw className="mr-2 inline h-4 w-4"/>Actualizar</button></div>
 {path.includes('/wallet')&&<><section className="qb-surface rounded-3xl border qb-border p-6"><p className="qb-text-secondary text-xs font-black uppercase tracking-widest">Saldo disponible</p><p className="mt-2 text-4xl font-black text-emerald-600">{money(data?.balance)}</p></section><section className="qb-surface rounded-3xl border qb-border p-6"><h2 className="qb-text text-xl font-black">Solicitar recarga</h2><div className="mt-4 grid gap-3 md:grid-cols-4"><input type="number" placeholder="Monto" value={topup.amount} onChange={e=>setTopup({...topup,amount:e.target.value})} className="rounded-xl border qb-border bg-transparent px-3 py-2"/><select value={topup.method} onChange={e=>setTopup({...topup,method:e.target.value})} className="rounded-xl border qb-border bg-transparent px-3 py-2"><option value="manual">Manual</option><option value="nequi">Nequi</option><option value="bre-b">Bre-B</option></select><input placeholder="Referencia" value={topup.reference} onChange={e=>setTopup({...topup,reference:e.target.value})} className="rounded-xl border qb-border bg-transparent px-3 py-2"/><button disabled={busy==='topup'} onClick={()=>void sendTopup()} className="rounded-xl bg-emerald-600 px-4 py-2 font-black text-white">Solicitar</button></div><input placeholder="Comentario" value={topup.comment} onChange={e=>setTopup({...topup,comment:e.target.value})} className="mt-3 w-full rounded-xl border qb-border bg-transparent px-3 py-2"/></section><section className="qb-surface rounded-3xl border qb-border p-6"><h2 className="qb-text text-xl font-black">Movimientos</h2><div className="mt-3 space-y-2">{(data?.transactions??[]).map((x:any)=><div key={x.id} className="flex justify-between rounded-2xl border qb-border p-3 text-sm"><span className="qb-text">{x.description}</span><span className="font-black">{money(x.amount)}</span></div>)}</div></section></>}
 {path.includes('/history')&&<section className="space-y-3">{(data?.items??[]).map((o:any)=><article key={o.id} className="qb-surface rounded-3xl border qb-border p-5"><div className="flex justify-between"><div><p className="qb-text font-black">#{o.order_number??o.pickup_code}</p><p className="qb-text-secondary text-sm">{new Date(o.created_at).toLocaleString('es-CO')}</p></div><span className="rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-black">{o.status}</span></div><p className="mt-3 qb-text font-black">{money(o.total)}</p></article>)}</section>}
 {path.includes('/favorites')&&<section className="grid gap-4 md:grid-cols-2">{(data?.items??[]).map((x:any)=><article key={x.id??x.product_id} className="qb-surface rounded-3xl border qb-border p-5"><div className="flex justify-between"><div><h2 className="qb-text font-black">{x.name}</h2><p className="qb-text-secondary text-sm">{x.description}</p><p className="mt-2 font-black text-emerald-600">{money(x.price)}</p></div><Heart className="h-5 w-5 text-rose-500"/></div><button disabled={busy===String(x.id??x.product_id)} onClick={async()=>{try{await quickbiteApi().removeFavorite(String(x.id??x.product_id));toast.success('Favorito eliminado.');await load()}catch(e){toast.error(e instanceof Error?e.message:'No se pudo eliminar.')}}} className="mt-4 rounded-xl border px-3 py-2 text-sm font-black">Quitar</button></article>)}</section>}
 {path.includes('/notifications')&&<section className="space-y-3">{(data?.items??[]).map((x:any)=><article key={x.id} className="qb-surface rounded-3xl border qb-border p-5"><div className="flex justify-between gap-3"><div><Bell className="mb-2 h-5 w-5 text-violet-500"/><h2 className="qb-text font-black">{x.title}</h2><p className="qb-text-secondary text-sm">{x.body}</p></div>{x.read_at?<span className="text-xs font-black text-emerald-600">Leída</span>:<button onClick={async()=>{await quickbiteApi().markNotificationRead(x.id);await load()}} className="rounded-xl border px-3 py-2 text-xs font-black">Marcar leída</button>}</div></article>)}</section>}
 {path.includes('/reviews')&&<section className="space-y-3">{(data?.purchases??[]).map((p:any)=>{const k=p.order_id+':'+p.product_id;const r=review[k]??{stars:0,comment:''};return <article key={k} className="qb-surface rounded-3xl border qb-border p-5"><h3 className="qb-text font-black">{p.product?.name??'Producto'}</h3><div className="mt-3 flex gap-2">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setReview({...review,[k]:{...r,stars:n}})}><Star className={r.stars>=n?'h-5 w-5 fill-amber-400 text-amber-500':'h-5 w-5'}/></button>)}</div><textarea value={r.comment} onChange={e=>setReview({...review,[k]:{...r,comment:e.target.value}})} className="mt-3 w-full rounded-xl border qb-border bg-transparent p-3" placeholder="Comentario"/><button onClick={async()=>{if(!r.stars)return toast.error('Selecciona estrellas.');try{await quickbiteApi().submitReview({orderId:p.order_id,productId:p.product_id,stars:r.stars,comment:r.comment});toast.success('Reseña enviada.');await load()}catch(e){toast.error(e instanceof Error?e.message:'No se pudo enviar.')}}} className="mt-3 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white">Enviar</button></article>})}</section>}
 {path.includes('/rewards')&&<><section className="qb-surface rounded-3xl border qb-border p-6"><p className="qb-text-secondary text-sm">Puntos disponibles</p><p className="mt-1 text-4xl font-black text-amber-500">{data?.availablePoints??0}</p></section><div className="grid gap-4 md:grid-cols-2">{(data?.rewards??[]).map((r:any)=><article key={r.reward_id} className="qb-surface rounded-3xl border qb-border p-5"><h2 className="qb-text font-black">{r.title}</h2><p className="qb-text-secondary mt-1 text-sm">{r.reward_description}</p><p className="mt-3 qb-text font-black">{r.points_required} puntos</p><button disabled={(data?.availablePoints??0)<r.points_required} onClick={async()=>{try{await quickbiteApi().redeemReward(r.reward_id);toast.success('Canje realizado.');await load()}catch(e){toast.error(e instanceof Error?e.message:'No se pudo canjear.')}}} className="mt-3 rounded-xl bg-amber-500 px-4 py-2 font-black text-white disabled:opacity-40">Canjear</button></article>)}</div></>}
 {path.includes('/link-code')&&<section className="qb-surface rounded-3xl border qb-border p-8 text-center"><Link2 className="mx-auto h-8 w-8 text-blue-500"/><p className="qb-text-secondary mt-3 text-sm">Código vigente</p><p className="mt-2 text-4xl font-black tracking-widest text-blue-600">{data?.code}</p><button onClick={async()=>{setBusy('code');try{setData(await quickbiteApi().studentLinkCode(true));toast.success('Nuevo código generado.')}catch(e){toast.error(e instanceof Error?e.message:'No se pudo generar.')}finally{setBusy(null)}}} className="mt-5 rounded-xl bg-blue-600 px-5 py-3 font-black text-white"><RefreshCw className="mr-2 inline h-4 w-4"/>Regenerar</button></section>}
 {path.includes('/account')&&<section className="qb-surface rounded-3xl border qb-border p-6 space-y-4"><label className="block qb-text font-black">Nombre<input className="mt-1 w-full rounded-xl border qb-border bg-transparent px-3 py-2" value={account.fullName} onChange={e=>setAccount({...account,fullName:e.target.value})}/></label><label className="block qb-text font-black">Preferencias alimentarias<input className="mt-1 w-full rounded-xl border qb-border bg-transparent px-3 py-2" placeholder="Vegetariano, sin lactosa..." value={account.dietaryPreferences} onChange={e=>setAccount({...account,dietaryPreferences:e.target.value})}/></label><label className="block qb-text font-black">Alergias<textarea className="mt-1 w-full rounded-xl border qb-border bg-transparent p-3" value={account.allergies} onChange={e=>setAccount({...account,allergies:e.target.value})}/></label><label className="block qb-text font-black">Notas<textarea className="mt-1 w-full rounded-xl border qb-border bg-transparent p-3" value={account.guardianNotes} onChange={e=>setAccount({...account,guardianNotes:e.target.value})}/></label><button disabled={busy==='account'} onClick={()=>void saveAccount()} className="rounded-xl bg-emerald-600 px-5 py-3 font-black text-white">Guardar cambios</button></section>}
 </div></main>;
}
