import { useCallback,useEffect,useMemo,useState } from 'react';
import { ArrowLeft,CheckCircle2,Clock3,Info,Power,RefreshCw,TimerReset } from 'lucide-react';
import { Link } from 'react-router-dom';
import { quickbiteApi } from '../../../services/api/quickbiteApi';

type WindowRow={slot_id:string;slot_name:string;starts_at:string;ends_at:string;enabled:boolean;max_orders:number|null;orders_count:number;accepting_orders:boolean};
const mins=(v:string)=>{const [h,m]=v.slice(0,5).split(':').map(Number);return h*60+m};
const nowBogota=()=>{const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Bogota',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());return Number(parts.find(x=>x.type==='hour')?.value??0)*60+Number(parts.find(x=>x.type==='minute')?.value??0)};
const label=(w:WindowRow)=>!w.enabled?'No disponible':w.accepting_orders?'Puedes pedir ahora':w.max_orders!==null&&w.orders_count>=w.max_orders?'Cupo lleno':'Fuera de horario';

export default function StudentOrderWindows(){
 const [items,setItems]=useState<WindowRow[]>([]);const [enabled,setEnabled]=useState(true);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const r=await quickbiteApi().orderWindows();setItems(r.items as WindowRow[]);setEnabled(r.enabled);setError('')}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar las ventanas.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),15000);return()=>window.clearInterval(t)},[load]);
 const ordered=useMemo(()=>[...items].sort((a,b)=>a.starts_at.localeCompare(b.starts_at)),[items]);const now=nowBogota();const active=enabled?ordered.find(x=>x.accepting_orders):undefined;const next=enabled?ordered.filter(x=>x.enabled&&!x.accepting_orders&&mins(x.starts_at)>now).sort((a,b)=>mins(a.starts_at)-mins(b.starts_at))[0]:undefined;const remaining=ordered.reduce((n,x)=>x.max_orders===null?n:n+Math.max(Number(x.max_orders)-Number(x.orders_count),0),0);
 return <main className="qb-page min-h-screen p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-5xl space-y-6"><div className="flex items-center justify-between"><div><Link to="/student/features" className="inline-flex items-center gap-2 text-sm font-bold text-emerald-700"><ArrowLeft className="h-4 w-4"/>Funciones</Link><h1 className="mt-3 qb-text text-3xl font-black">Ventanas de pedidos</h1><p className="qb-text-secondary mt-1 text-sm">Consulta horarios y cupos directamente desde QuickBite Core.</p></div><button onClick={()=>void load()} className="rounded-xl border qb-border qb-surface px-4 py-2 text-sm font-bold"><RefreshCw className="mr-2 inline h-4 w-4"/>Actualizar</button></div>
 {error&&<div className="rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm font-semibold text-amber-800">{error}</div>}
 {!enabled&&<div className="flex gap-3 rounded-2xl border border-amber-300 bg-amber-50 p-4 text-amber-900"><Power className="h-5 w-5 shrink-0"/><div><b>Ventanas desactivadas</b><p className="text-sm">Los pedidos siguen disponibles sin esta restricción.</p></div></div>}
 <div className="grid gap-4 md:grid-cols-3"><div className="qb-surface rounded-2xl border qb-border p-4"><p className="qb-text-secondary text-xs font-black uppercase">Estado ahora</p><p className="qb-text mt-1 font-black">{active?.slot_name??(enabled?'Pedidos cerrados':'Sin restricción')}</p></div><div className="qb-surface rounded-2xl border qb-border p-4"><p className="qb-text-secondary text-xs font-black uppercase">Próxima</p><p className="qb-text mt-1 font-black">{next?.slot_name??'Sin horarios'}</p>{next&&<p className="qb-text-secondary text-xs">{next.starts_at.slice(0,5)} – {next.ends_at.slice(0,5)}</p>}</div><div className="qb-surface rounded-2xl border qb-border p-4"><p className="qb-text-secondary text-xs font-black uppercase">Cupos restantes</p><p className="qb-text mt-1 text-2xl font-black">{ordered.some(x=>x.max_orders===null)?'Sin límite':remaining}</p></div></div>
 {loading?<div className="qb-surface rounded-3xl border qb-border p-8">Cargando ventanas...</div>:ordered.length===0?<div className="qb-surface rounded-3xl border qb-border p-8 text-center"><Clock3 className="mx-auto h-10 w-10 text-slate-400"/><p className="qb-text mt-3 font-black">No hay ventanas configuradas.</p></div>:<div className="grid gap-4 lg:grid-cols-2">{ordered.map(w=>{const left=w.max_orders===null?null:Math.max(w.max_orders-w.orders_count,0);const progress=w.max_orders?Math.min(w.orders_count/w.max_orders*100,100):0;const isActive=enabled&&w.accepting_orders;return <article key={w.slot_id} className="qb-surface rounded-3xl border qb-border p-5"><div className="flex justify-between gap-3"><div className="flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-slate-100 dark:bg-slate-800">{isActive?<CheckCircle2 className="h-5 w-5 text-emerald-500"/>:<TimerReset className="h-5 w-5 text-slate-500"/>}</div><div><h2 className="qb-text font-black">{w.slot_name}</h2><p className="qb-text-secondary text-sm"><Clock3 className="mr-1 inline h-4 w-4"/>{w.starts_at.slice(0,5)} – {w.ends_at.slice(0,5)}</p></div></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black dark:bg-slate-800">{label(w)}</span></div><div className="mt-4 rounded-2xl border qb-border p-4"><div className="flex justify-between text-sm"><span className="qb-text-secondary">Capacidad</span><b className="qb-text">{w.max_orders===null?String(w.orders_count)+' pedidos':String(w.orders_count)+'/'+String(w.max_orders)}</b></div>{w.max_orders!==null&&<><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-800"><div className="h-full rounded-full bg-emerald-500" style={{width:String(progress)+'%'}}/></div><p className="qb-text-secondary mt-2 text-xs">{left===0?'Sin cupos disponibles':String(left)+' cupos restantes'}</p></>}</div>{isActive&&<p className="mt-3 flex items-center gap-2 rounded-xl bg-emerald-500/10 p-3 text-sm font-bold text-emerald-700 dark:text-emerald-300"><CheckCircle2 className="h-4 w-4"/>Puedes entrar al menú y comprar ahora.</p>}</article>})}</div>}
 <div className="flex items-center justify-center gap-2 text-xs qb-text-secondary"><Info className="h-4 w-4"/>Estado actualizado automáticamente.</div></div></main>;
}
