import { useEffect,useState } from 'react';
import { ArrowLeft,Check,RefreshCw,ShieldCheck,X } from 'lucide-react';
import { Link,useLocation } from 'react-router-dom';
import { toast } from 'sonner';
import { quickbiteApi,type ApiOrder } from '../../../services/api/quickbiteApi';

const money=(n:number)=>'$'+Number(n||0).toLocaleString('es-CO');
const statusLabel=(s:string)=>({pending:'Pendiente',preparing:'Preparando',ready:'Listo',delivered:'Entregado',cancelled:'Cancelado'} as Record<string,string>)[s]??s;

export function CoreAdminFeaturePage(){
 const path=useLocation().pathname; const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const [code,setCode]=useState(''); const [confirmation,setConfirmation]=useState(''); const [period,setPeriod]=useState({start:new Date(Date.now()-7*86400000).toISOString().slice(0,10),end:new Date().toISOString().slice(0,10)});
 const load=async()=>{setLoading(true);try{
   if(path==='/admin'||path.includes('/operations')||path.includes('/rankings')){const [o,d]=await Promise.all([quickbiteApi().orders(),quickbiteApi().adminDashboard(30)]);setData({orders:o.items,dashboard:d});}
   else if(path.includes('/orders'))setData((await quickbiteApi().orders()).items);
   else if(path.includes('/payments'))setData((await quickbiteApi().orders()).items.filter((o:any)=>o.payment_status==='pending'));
   else if(path.includes('/wallet'))setData(await quickbiteApi().adminWalletTopups());
   else if(path.includes('/menu'))setData(await quickbiteApi().adminProducts());
   else if(path.includes('/inventory'))setData(await quickbiteApi().adminProducts());
   else if(path.includes('/nutrition')){const [p,n]=await Promise.all([quickbiteApi().adminProducts(),quickbiteApi().nutrition()]);setData({products:p.products,nutrition:n.items});}
   else if(path.includes('/reviews'))setData(await quickbiteApi().adminReviews());
   else if(path.includes('/loyalty'))setData(await quickbiteApi().adminLoyalty());
   else if(path.includes('/reports'))setData(null);
   else if(path.includes('/history'))setData(await quickbiteApi().adminHistory());
   else if(path.includes('/system'))setData(await quickbiteApi().adminSystem());
   else if(path.includes('/verification'))setData(null);
   else if(path.includes('/reset'))setData(null);
 }catch(e){toast.error(e instanceof Error?e.message:'No se pudo cargar el módulo.')}finally{setLoading(false)}};useEffect(()=>{void load()},[path]);

 if(loading)return <div className="grid min-h-[60vh] place-items-center"><RefreshCw className="h-6 w-6 animate-spin"/></div>;
 const heading=path==='/admin'?'Dashboard':path.includes('/orders')?'Pedidos':path.includes('/payments')?'Pagos':path.includes('/wallet')?'Recargas':path.includes('/menu')?'Menú y productos':path.includes('/inventory')?'Inventario':path.includes('/nutrition')?'Nutrición':path.includes('/reviews')?'Reseñas':path.includes('/loyalty')?'Puntos y recompensas':path.includes('/reports')?'Informes':path.includes('/history')?'Auditoría y cancelaciones':path.includes('/system')?'Estado del sistema':path.includes('/verification')?'Verificación de pedidos':'Reiniciar período';

 const changeStatus=async(id:string,s:ApiOrder['status'])=>{setBusy(id);try{await quickbiteApi().updateOrderStatus(id,s);toast.success('Estado actualizado.');await load()}catch(e){toast.error(e instanceof Error?e.message:'No se pudo actualizar.')}finally{setBusy(null)}};
 return <section className="space-y-5"><div className="flex items-center justify-between gap-3"><div><Link to="/admin/features" className="inline-flex items-center gap-2 text-xs font-black text-blue-700"><ArrowLeft className="h-4 w-4"/>Funciones</Link><h1 className="mt-2 text-3xl font-black text-[var(--qb-text)]">{heading}</h1></div><button onClick={()=>void load()} className="rounded-xl border bg-white px-4 py-2 text-sm font-black"><RefreshCw className="mr-2 inline h-4 w-4"/>Actualizar</button></div>
 {path==='/admin'&&<><div className="grid gap-4 md:grid-cols-4">{[['Pedidos',data?.orders?.length??0],['Pendientes',(data?.orders??[]).filter((x:any)=>x.status==='pending').length],['Listos',(data?.orders??[]).filter((x:any)=>x.status==='ready').length],['Ingresos',money((data?.dashboard?.daily??[]).reduce((a:any,x:any)=>a+Number(x.revenue||0),0))]].map(x=><div key={String(x[0])} className="rounded-3xl border bg-white p-5"><p className="text-sm text-slate-500">{x[0]}</p><p className="mt-1 text-2xl font-black">{x[1]}</p></div>)}</div><div className="rounded-3xl border bg-white p-6"><h2 className="text-xl font-black">Actividad reciente</h2>{(data?.orders??[]).slice(0,12).map((o:any)=><div key={o.id} className="flex items-center justify-between border-b py-3 text-sm"><span className="font-bold">#{o.pickup_code}</span><span>{statusLabel(o.status)}</span><strong>{money(o.total)}</strong></div>)}</div></>}
 {((path.includes('/orders')))&&<div className="space-y-3">{(Array.isArray(data)?data:[]).map((o:any)=><article key={o.id} className="rounded-3xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-black">#{o.pickup_code}</p><p className="text-xs text-slate-500">{new Date(o.created_at).toLocaleString('es-CO')}</p></div><strong>{money(o.total)}</strong></div><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{statusLabel(o.status)}</span>{(['preparing','ready','delivered','cancelled'] as const).filter(s=>s!==o.status).map(s=><button key={s} disabled={busy===o.id} onClick={()=>void changeStatus(o.id,s)} className="rounded-xl border px-3 py-2 text-xs font-black">{statusLabel(s)}</button>)}</div></article>)}</div>}
 {path.includes('/payments')&&<div className="space-y-3">{(data??[]).map((o:any)=><article key={o.id} className="flex flex-wrap items-center justify-between gap-4 rounded-3xl border bg-white p-5"><div><p className="font-black">#{o.pickup_code}</p><p className="text-sm text-slate-500">Método: {o.payment_method}</p><p className="font-black">{money(o.total)}</p></div><div className="flex gap-2"><button onClick={async()=>{try{await quickbiteApi().moderatePayment(o.id,'approve');toast.success('Pago aprobado.');await load()}catch(e){toast.error(e instanceof Error?e.message:'No se pudo aprobar.')}}} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-black text-white"><Check className="mr-1 inline h-4 w-4"/>Aprobar</button><button onClick={async()=>{try{await quickbiteApi().moderatePayment(o.id,'reject');toast.success('Pago rechazado.');await load()}catch(e){toast.error(e instanceof Error?e.message:'No se pudo rechazar.')}}} className="rounded-xl bg-rose-600 px-4 py-2 text-sm font-black text-white"><X className="mr-1 inline h-4 w-4"/>Rechazar</button></div></article>)}</div>}
 {path.includes('/wallet')&&<div className="space-y-3">{(data?.items??[]).map((r:any)=><article key={r.id} className="rounded-3xl border bg-white p-5"><div className="flex justify-between"><div><p className="font-black">{r.full_name}</p><p className="text-sm text-slate-500">{r.email} · {r.method}</p><p className="text-xl font-black text-emerald-700">{money(r.amount)}</p></div><span className="text-xs font-black">{r.status}</span></div>{r.status==='pending'&&<div className="mt-3 flex gap-2"><button onClick={async()=>{await quickbiteApi().moderateWalletTopup(r.id,'approve');await load()}} className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white">Aprobar</button><button onClick={async()=>{await quickbiteApi().moderateWalletTopup(r.id,'reject');await load()}} className="rounded-xl bg-rose-600 px-4 py-2 text-xs font-black text-white">Rechazar</button></div>}</article>)}</div>}
 {path.includes('/menu')&&<Menu data={data} reload={load}/>}
 {path.includes('/inventory')&&<Inventory data={data} reload={load}/>}
 {path.includes('/nutrition')&&<Nutrition data={data} reload={load}/>}
 {path.includes('/reviews')&&<Reviews data={data} reload={load}/>}
 {path.includes('/loyalty')&&<Loyalty data={data} reload={load}/>}
 {path.includes('/reports')&&<section className="rounded-3xl border bg-white p-6"><div className="grid gap-3 md:grid-cols-2"><label className="text-sm font-black">Desde<input type="date" value={period.start} onChange={e=>setPeriod({...period,start:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="text-sm font-black">Hasta<input type="date" value={period.end} onChange={e=>setPeriod({...period,end:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"/></label></div><button onClick={async()=>{try{setData(await quickbiteApi().adminReports(period.start+'T00:00:00',period.end+'T23:59:59'));}catch(e){toast.error(e instanceof Error?e.message:'No se pudo generar.')}}} className="mt-4 rounded-xl bg-blue-600 px-4 py-2 font-black text-white">Generar informe</button>{data?.items&&<div className="mt-4 space-y-2">{data.items.map((o:any)=><div key={o.id} className="flex justify-between border-b py-2 text-sm"><span>#{o.pickup_code}</span><span>{money(o.total)}</span></div>)}</div>}</section>}
 {path.includes('/history')&&<section className="space-y-3">{(data?.cancellations??[]).map((r:any)=><article key={r.id} className="rounded-3xl border bg-white p-5"><p className="font-black">Cancelación #{r.order_number}</p><p className="text-sm text-slate-500">{r.reason}</p><p className="mt-1 text-xs">{r.status}</p>{r.status==='pending'&&<div className="mt-3 flex gap-2"><button onClick={async()=>{await quickbiteApi().reviewCancellation(r.id,true);await load()}} className="rounded-xl bg-emerald-600 px-4 py-2 text-xs font-black text-white">Aprobar</button><button onClick={async()=>{await quickbiteApi().reviewCancellation(r.id,false);await load()}} className="rounded-xl bg-rose-600 px-4 py-2 text-xs font-black text-white">Rechazar</button></div>}</article>)}<h2 className="pt-4 text-xl font-black">Eventos</h2>{(data?.audits??[]).slice(0,100).map((a:any)=><div key={a.id} className="border-b py-2 text-xs">{a.created_at} · {a.action}</div>)}</section>}
 {path.includes('/system')&&<section className="rounded-3xl border bg-white p-6"><div className="grid gap-3 md:grid-cols-3"><div><p className="text-sm text-slate-500">Eventos</p><p className="text-2xl font-black">{data?.audit_events??0}</p></div><div><p className="text-sm text-slate-500">Alertas</p><p className="text-2xl font-black">{data?.open_alerts??0}</p></div><div><p className="text-sm text-slate-500">Servicios</p><p className="text-2xl font-black">{data?.health?.length??0}</p></div></div></section>}
 {path.includes('/verification')&&<section className="max-w-xl rounded-3xl border bg-white p-6"><label className="block text-sm font-black">Código de recogida<input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} className="mt-1 w-full rounded-xl border px-3 py-3 text-2xl font-black tracking-widest" placeholder="AB12CD34"/></label><button onClick={async()=>{try{const r=await quickbiteApi().verifyPickup(code);toast.success(r.alreadyDelivered?'El pedido ya estaba entregado.':'Recogida verificada y pedido entregado.');setCode('')}catch(e){toast.error(e instanceof Error?e.message:'Código inválido.')}}} className="mt-4 rounded-xl bg-blue-700 px-5 py-3 font-black text-white"><ShieldCheck className="mr-2 inline h-4 w-4"/>Verificar</button></section>}
 {path.includes('/reset')&&<section className="max-w-2xl rounded-3xl border border-red-200 bg-white p-6"><p className="text-sm text-red-700">Esta acción elimina el flujo operativo de prueba.</p><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder="REINICIAR" className="mt-4 w-full rounded-xl border px-3 py-3 font-black"/><button disabled={confirmation.toUpperCase()!=='REINICIAR'} onClick={async()=>{try{await quickbiteApi().resetPeriod(confirmation);toast.success('Período reiniciado.');setConfirmation('');await load()}catch(e){toast.error(e instanceof Error?e.message:'No se pudo reiniciar.')}}} className="mt-4 rounded-xl bg-red-600 px-5 py-3 font-black text-white">Reiniciar período</button></section>}
 </section>;
}
function Menu({data,reload}:{data:any;reload:()=>Promise<void>}){const [form,setForm]=useState({name:'',description:'',price:'',stock:'',categoryId:'',imageUrl:''});return <section className="space-y-4"><div className="rounded-3xl border bg-white p-6"><div className="grid gap-3 md:grid-cols-5">{(['name','description','price','stock','imageUrl'] as const).map(k=><input key={k} placeholder={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="rounded-xl border px-3 py-2"/>)}</div><button onClick={async()=>{try{await quickbiteApi().createProduct({...form,price:Number(form.price),stock:Number(form.stock),categoryId:form.categoryId||undefined});toast.success('Producto creado.');setForm({name:'',description:'',price:'',stock:'',categoryId:'',imageUrl:''});await reload()}catch(e){toast.error(e instanceof Error?e.message:'No se pudo crear.')}}} className="mt-3 rounded-xl bg-blue-600 px-4 py-2 font-black text-white">Agregar producto</button></div><div className="grid gap-3 md:grid-cols-2">{(data?.products??[]).map((p:any)=><article key={p.id} className="rounded-3xl border bg-white p-5"><p className="font-black">{p.name}</p><p>{money(p.price)} · stock {p.stock}</p><div className="mt-3 flex gap-2"><button onClick={async()=>{const n=window.prompt('Nuevo stock',String(p.stock));if(n==null)return;await quickbiteApi().updateProduct(p.id,{stock:Number(n)});await reload()}} className="rounded-xl border px-3 py-2 text-xs font-black">Editar stock</button><button onClick={async()=>{if(!window.confirm('Eliminar producto?'))return;await quickbiteApi().deleteProduct(p.id);await reload()}} className="rounded-xl border px-3 py-2 text-xs font-black text-red-600">Eliminar</button></div></article>)}</div></section>}
function Inventory({data,reload}:{data:any;reload:()=>Promise<void>}){const [id,setId]=useState('');const [stock,setStock]=useState('');return <section className="space-y-3"><div className="rounded-3xl border bg-white p-6"><select value={id} onChange={e=>{setId(e.target.value);const p=data?.products?.find((x:any)=>x.id===e.target.value);setStock(String(p?.stock??''))}} className="w-full rounded-xl border px-3 py-2"><option value="">Producto</option>{(data?.products??[]).map((p:any)=><option key={p.id} value={p.id}>{p.name} · {p.stock}</option>)}</select><input value={stock} onChange={e=>setStock(e.target.value)} className="mt-3 w-full rounded-xl border px-3 py-2" type="number"/><button onClick={async()=>{if(!id)return;await quickbiteApi().adjustInventory({productId:id,newStock:Number(stock),reason:'Ajuste administrativo'});toast.success('Stock actualizado.');await reload()}} className="mt-3 rounded-xl bg-blue-600 px-4 py-2 font-black text-white">Guardar</button></div></section>}
function Nutrition({data,reload}:{data:any;reload:()=>Promise<void>}){const [productId,setProductId]=useState('');const [form,setForm]=useState<any>({calories:'',proteinG:'',carbohydratesG:'',fatG:'',fiberG:'',ingredients:'',allergens:'',vegetarian:false,healthyChoice:false});return <section className="rounded-3xl border bg-white p-6"><select value={productId} onChange={e=>setProductId(e.target.value)} className="w-full rounded-xl border px-3 py-2"><option value="">Producto</option>{(data?.products??[]).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="mt-3 grid gap-3 md:grid-cols-3">{['calories','proteinG','carbohydratesG','fatG','fiberG','ingredients','allergens'].map(k=><input key={k} placeholder={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="rounded-xl border px-3 py-2"/>)}</div><button onClick={async()=>{await quickbiteApi().saveNutrition({...form,productId});toast.success('Información nutricional guardada.');await reload()}} className="mt-3 rounded-xl bg-emerald-600 px-4 py-2 font-black text-white">Guardar nutrición</button></section>}
function Reviews({data,reload}:{data:any;reload:()=>Promise<void>}){return <section className="space-y-3">{(data?.items??[]).map((r:any)=><article key={r.id} className="rounded-3xl border bg-white p-5"><div className="flex justify-between"><div><p className="font-black">{r.product_name}</p><p className="text-sm text-slate-500">{r.student_name} · {r.stars}/5</p><p className="mt-2 text-sm">{r.comment||'Sin comentario'}</p></div><span className="text-xs font-black">{r.status}</span></div>{r.status==='pending'&&<div className="mt-3 flex gap-2"><button onClick={async()=>{await quickbiteApi().moderateReview(r.id,'approved');await reload()}} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-black text-white">Aprobar</button><button onClick={async()=>{await quickbiteApi().moderateReview(r.id,'rejected');await reload()}} className="rounded-xl bg-rose-600 px-3 py-2 text-xs font-black text-white">Rechazar</button></div>}</article>)}</section>}
function Loyalty({data,reload}:{data:any;reload:()=>Promise<void>}){return <section className="space-y-3"><div className="rounded-3xl border bg-white p-6"><p className="font-black">Programa: {data?.settings?.enabled?'Activo':'Inactivo'}</p><button onClick={async()=>{await quickbiteApi().setLoyaltyEnabled(!data?.settings?.enabled);await reload()}} className="mt-3 rounded-xl bg-blue-600 px-4 py-2 font-black text-white">Cambiar estado</button></div>{(data?.rewards??[]).map((r:any)=><div key={r.reward_id} className="rounded-3xl border bg-white p-5"><p className="font-black">{r.title}</p><p>{r.points_required} puntos · {r.product_name}</p></div>)}</section>}
